# Generated by Django 3.2 on 2022-08-28 19:29

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YoloClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None)),
                ('photos', models.ManyToManyField(blank=True, related_name='yolo_classes', to='web.Photo')),
            ],
            options={
                'verbose_name': 'Yolo class',
                'verbose_name_plural': 'Yolo classes',
            },
        ),
        migrations.CreateModel(
            name='YoloObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('accuracy', models.FloatField()),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yolo_objects', to='web.photo')),
                ('yolo_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yolo.yoloclass')),
            ],
        ),
    ]
