# Generated by Django 3.2 on 2022-09-20 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoproject',
            name='is_ai_tag',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photoproject',
            name='match',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photoproject',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meta', to='web.photo'),
        ),
        migrations.AlterField(
            model_name='photoproject',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meta', to='web.project'),
        ),
    ]
